name: Ping
on:
  repository_dispatch:
    types: [ping-command]
jobs:
  pong:
    runs-on: ubuntu-latest
    steps:
      - name: Update comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.NOTIFICATION }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          body: |
            >pong ${{ github.event.client_payload.slash_command.args }}
          reaction-type: hooray
