name: Promote
on:
  repository_dispatch:
    types: [deploy-command]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_BASE: docker.pkg.github.com/${{ github.repository }}/fpsoknad-mottak
      
jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
    
      - name: Set imagenavn og cluster fra args
        run: |
           echo "::set-env name=SHA::$(echo $GITHUB_SHA | cut -c1-7)"  
           echo "::set-env name=IMAGE::$IMAGE_BASE:${{ github.event.client_payload.slash_command.arg1 }}" 
           echo "::set-env name=CLUSTER::${{ github.event.client_payload.slash_command.arg2 }}" 
         
      - run: |
         echo "SHA er $SHA"
         
      - name: Sjekk ut kode
        uses: actions/checkout@v1
        with:
          ref: ${{env.SHA}}
       
      - name: Promote til cluster
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ env.CLUSTER }}
          RESOURCE: naiserator1.yaml
          PRINT_PAYLOAD: true
          VARS: ${{ env.CLUSTER }}.json 
          
      - name: Oppdater kommentar med deployment status ved feil
        if: failure()
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.NOTIFICATION }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          body: |
            >promote ${{ env.IMAGE }} til ${{ env.CLUSTER }} feilet
          reaction-type: -1          
 
      - name: Oppdater kommentar med deployment status
        if: success()
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.NOTIFICATION }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          body: |
            >promote ${{ env.IMAGE }} til ${{ env.CLUSTER }} var OK
          reaction-type: rocket
                  
